_uncategorized = [ //to be sorted, civilian stuff etc.
	"CUP_U_O_CHDKZ_Lopotev",
	"CUP_U_C_Citizen_02",
	"CUP_U_C_Citizen_01",
	"CUP_U_C_Citizen_04",
	"CUP_U_C_Citizen_03",
	"CUP_U_C_Priest_01",
	"CUP_U_CRYE_ATACSAU_Full",
	"CUP_U_CRYE_ATACSAU_Roll",
	"CUP_U_CRYE_ATACSFG_Full",
	"CUP_U_CRYE_ATACSFG_Roll",
	"CUP_U_CRYE_BLK_Full",
	"CUP_U_CRYE_BLK_Roll",
	"CUP_U_CRYE_BLK_RUS_Full",
	"CUP_U_CRYE_BLK_RUS_Roll",
	"CUP_U_CRYE_G3C_AOR1",
	"CUP_U_CRYE_G3C_AOR2",
	"CUP_U_CRYE_G3C_ATACSAU",
	"CUP_U_CRYE_G3C_ATACSFG",
	"CUP_U_CRYE_G3C_BLK",
	"CUP_U_CRYE_G3C_M81_Tan_US",
	"CUP_U_CRYE_G3C_M81_Tan",
	"CUP_U_C_Fireman_01",
	"CUP_O_TKI_Khet_Jeans_04",
	"CUP_O_TKI_Khet_Jeans_02",
	"CUP_O_TKI_Khet_Jeans_01",
	"CUP_O_TKI_Khet_Jeans_03",
	"CUP_O_TKI_Khet_Partug_04",
	"CUP_O_TKI_Khet_Partug_02",
	"CUP_O_TKI_Khet_Partug_01",
	"CUP_O_TKI_Khet_Partug_07",
	"CUP_O_TKI_Khet_Partug_08",
	"CUP_O_TKI_Khet_Partug_05",
	"CUP_O_TKI_Khet_Partug_06",
	"CUP_O_TKI_Khet_Partug_03",
	"CUP_U_C_Labcoat_02",
	"CUP_U_C_Labcoat_03",
	"CUP_U_C_Labcoat_01",
	"CUP_U_C_Mechanic_02",
	"CUP_U_C_Mechanic_03",
	"CUP_U_C_Mechanic_01",
	"CUP_U_I_GUE_Anorak_01",
	"CUP_U_I_GUE_Anorak_03",
	"CUP_U_I_GUE_Anorak_02",
	"CUP_U_I_GUE_Woodland1",
	"CUP_U_USNavy_LHD_crew_Brown",
	"CUP_U_USNavy_LHD_crew_Green",
	"CUP_U_USNavy_LHD_crew_Red",
	"CUP_U_USNavy_LHD_crew_Violet",
	"CUP_U_USNavy_LHD_crew_White",
	"CUP_U_USNavy_LHD_crew_Yellow",
	"CUP_U_C_Rescuer_01",
	"CUP_U_C_Pilot_01",
	"CUP_I_B_PMC_Unit_20",
	"CUP_I_B_PMC_Unit_21",
	"CUP_I_B_PMC_Unit_19",
	"CUP_I_B_PMC_Unit_17",
	"CUP_I_B_PMC_Unit_13",
	"CUP_I_B_PMC_Unit_14",
	"CUP_I_B_PMC_Unit_15",
	"CUP_I_B_PMC_Unit_3",
	"CUP_I_B_PMC_Unit_2",
	"CUP_I_B_PMC_Unit_1",
	"CUP_I_B_PMC_Unit_4",
	"CUP_I_B_PMC_Unit_7",
	"CUP_I_B_PMC_Unit_6",
	"CUP_I_B_PMC_Unit_5",
	"CUP_I_B_PMC_Unit_8",
	"CUP_I_B_PMC_Unit_11",
	"CUP_I_B_PMC_Unit_10",
	"CUP_I_B_PMC_Unit_9",
	"CUP_I_B_PMC_Unit_12",
	"CUP_I_B_PMC_Unit_42",
	"CUP_I_B_PMC_Unit_41",
	"CUP_I_B_PMC_Unit_43",
	"CUP_I_B_PMC_Unit_40",
	"CUP_I_B_PMC_Unit_39",
	"CUP_I_B_PMC_Unit_36",
	"CUP_I_B_PMC_Unit_38",
	"CUP_I_B_PMC_Unit_37",
	"CUP_I_B_PMC_Unit_24",
	"CUP_I_B_PMC_Unit_23",
	"CUP_I_B_PMC_Unit_31",
	"CUP_I_B_PMC_Unit_32",
	"CUP_U_C_Policeman_01",
	"CUP_U_C_Profiteer_02",
	"CUP_U_C_Profiteer_03",
	"CUP_U_C_Profiteer_01",
	"CUP_U_C_Profiteer_04",
	"CUP_U_C_racketeer_01",
	"CUP_U_C_racketeer_02",
	"CUP_U_C_racketeer_03",
	"CUP_U_C_racketeer_04",
	"CUP_U_C_Rocker_01",
	"CUP_U_C_Rocker_03",
	"CUP_U_C_Rocker_02",
	"CUP_U_C_Rocker_04",
	"CUP_U_O_SLA_Overalls_Pilot",
	"CUP_U_O_SLA_Overalls_Tank",
	"CUP_U_C_Suit_01",
	"CUP_U_C_Suit_02",
	"CUP_U_C_Suit_03",
	"CUP_U_C_Functionary_jacket_02",
	"CUP_U_C_Functionary_jacket_01",
	"CUP_U_C_Functionary_jacket_03",
	"CUP_U_C_Villager_01",
	"CUP_U_C_Villager_04",
	"CUP_U_C_Villager_02",
	"CUP_U_C_Villager_03",
	"CUP_U_C_Woodlander_01",
	"CUP_U_C_Woodlander_02",
	"CUP_U_C_Woodlander_03", //wdl camo pants
	"CUP_U_C_Woodlander_04",
	"CUP_U_C_Worker_03",
	"CUP_U_C_Worker_04",
	"CUP_U_C_Worker_02",
	"CUP_U_C_Worker_01",
	"CUP_V_B_LHDVest_Blue",
	"CUP_V_B_LHDVest_Brown",
	"CUP_V_B_LHDVest_Green",
	"CUP_V_B_LHDVest_Red",
	"CUP_V_B_LHDVest_Violet",
	"CUP_V_B_LHDVest_White",
	"CUP_V_B_LHDVest_Yellow",
	"CUP_V_OI_TKI_Jacket1_04",
	"CUP_V_OI_TKI_Jacket1_06",
	"CUP_V_OI_TKI_Jacket1_05",
	"CUP_V_OI_TKI_Jacket4_04",
	"CUP_V_OI_TKI_Jacket4_05",
	"CUP_V_OI_TKI_Jacket4_06",
	"CUP_V_OI_TKI_Jacket5_04",
	"CUP_V_OI_TKI_Jacket5_05",
	"CUP_V_OI_TKI_Jacket5_06",
	"CUP_V_OI_TKI_Jacket3_04",
	"CUP_V_OI_TKI_Jacket3_05",
	"CUP_V_OI_TKI_Jacket3_06",
	"CUP_V_OI_TKI_Jacket6_04",
	"CUP_V_OI_TKI_Jacket6_05",
	"CUP_V_OI_TKI_Jacket6_06",
	"CUP_V_OI_TKI_Jacket2_04",
	"CUP_V_OI_TKI_Jacket2_06",
	"CUP_V_OI_TKI_Jacket2_05",
	"CUP_H_C_Beanie_01",
	"CUP_H_C_Beanie_02",
	"CUP_H_C_Beanie_03",
	"CUP_H_C_Beanie_04",
	"CUP_H_C_Beret_04",
	"CUP_H_C_Beret_01",
	"CUP_H_C_Beret_02",
	"CUP_H_C_Beret_03",
	"CUP_H_Ger_Beret_KSK_Red",
	"CUP_H_RUS_Beret_Spetsnaz",
	"CUP_H_RUS_Beret_VDV",
	"CUP_H_CZ_Hat01",
	"CUP_H_BAF_PARA_BERET",
	"CUP_H_CDF_Beret_UN",
	"CUP_H_BAF_PARA_PRRUNDER_BERET",
	"CUP_H_RACS_Beret_Blue",
	"CUP_H_SLA_BeretRed",
	"CUP_H_C_MAGA_01",
	"CUP_H_C_Policecap_01",
	"CUP_H_C_TrackIR_01",
	"CUP_H_USA_Cap_AU_DEF",
	"CUP_H_USA_Cap_NY_DEF",
	"CUP_H_USA_Cap_PUNISHER_DEF",
	"CUP_H_USA_Cap_UT_DEF",
	"CUP_H_PMC_Cap_Burberry",
	"CUP_H_PMC_Cap_Back_Burberry",
	"CUP_H_PMC_Cap_Back_PRR_Burberry",
	"CUP_H_PMC_Cap_PRR_Burberry",
	"CUP_H_PMC_EP_Headset",
	"CUP_H_C_Fireman_Helmet_01",
	"CUP_H_RUS_GSSh01_Headphones_black",
	"CUP_H_RUS_GSSh01_Headphones_brown",
	"CUP_H_RUS_GSSh01_Headphones_green",
	"CUP_H_RUS_GSSh01_Headphones_grey",
	"CUP_H_FR_Headband_Headset",
	"CUP_H_FR_Headset",
	"CUP_H_Navy_CrewHelmet_Blue",
	"CUP_H_Navy_CrewHelmet_Brown",
	"CUP_H_Navy_CrewHelmet_Green",
	"CUP_H_Navy_CrewHelmet_Red",
	"CUP_H_Navy_CrewHelmet_Violet",
	"CUP_H_Navy_CrewHelmet_White",
	"CUP_H_Navy_CrewHelmet_Yellow",
	"CUP_H_SLA_OfficerCap",
	"CUP_U_O_SLA_Officer_Suit",
	"CUP_H_CDF_OfficerCap_UN",
	"CUP_H_OpsCore_Covered_AAF",
	"CUP_H_OpsCore_Covered_AAF_NoHS",
	"CUP_H_OpsCore_Covered_AAF_SF",
	"CUP_H_CZ_Pakol_headset_f_brown",
	"CUP_H_CZ_Pakol_headset_b_grey",
	"CUP_H_CDF_H_PASGT_UN",
	"CUP_H_PMC_PRR_Headset",
	"CUP_H_TKI_Lungee_Open_01",
	"CUP_H_TKI_Lungee_Open_02",
	"CUP_H_TKI_Lungee_Open_03",
	"CUP_H_TKI_Lungee_Open_04",
	"CUP_H_TKI_Lungee_Open_05",
	"CUP_H_TKI_Lungee_Open_06",
	"CUP_H_TKI_Lungee_01",
	"CUP_H_TKI_Lungee_03",
	"CUP_H_TKI_Lungee_04",
	"CUP_H_TKI_Lungee_05",
	"CUP_H_TKI_Lungee_06",
	"CUP_H_TKI_Pakol_1_01",
	"CUP_H_TKI_Pakol_1_03",
	"CUP_H_TKI_Pakol_1_04",
	"CUP_H_TKI_Pakol_1_05",
	"CUP_H_TKI_Pakol_1_06",
	"CUP_H_TKI_Pakol_2_01",
	"CUP_H_TKI_Pakol_2_02",
	"CUP_H_TKI_Pakol_2_03",
	"CUP_H_TKI_Pakol_2_04",
	"CUP_H_TKI_Pakol_2_05",
	"CUP_H_TKI_Pakol_2_06",
	"CUP_H_TKI_SkullCap_01",
	"CUP_H_TKI_SkullCap_02",
	"CUP_H_TKI_SkullCap_03",
	"CUP_H_TKI_SkullCap_04",
	"CUP_H_TKI_SkullCap_05",
	"CUP_H_TKI_SkullCap_06",
	"CUP_H_RUS_ZSH_Shield_Up",
	"CUP_H_RUS_ZSH_Shield_Down"
];

_wood = [
	//terrains
	"#GdtGrassGreen",
	"#GdtStonyThistle",
	"#GdtStratisForestPine",
	"#Grass",
	"#GrassSouth",
	"#CRGrass1",
	"#CRGrassW1",
	"#CRForest1",
	"#CRForest2",
	"#CRHlina",
	"#CRSGrass1",
	"#CRSGrassW1",
	"#CRSForest1",
	"#CRSForest2",
	"#CRSHlina",
	//Takistan
	"#TKPole", //semi-lush grass, used for the farm fields
	//Zargabad
	"#ZRPole", //semi-lush grass, used for the farm fields
	//uniforms
	"U_O_CombatUniform_ocamo",
	"U_O_SpecopsUniform_ocamo",
	"U_O_OfficerUniform_ocamo",
	"U_O_V_Soldier_Viper_hex_F",
	"U_B_CombatUniform_mcam",
	"U_B_CombatUniform_mcam_tshirt",
	"U_B_CombatUniform_mcam_vest",
	// vests
	"V_HarnessO_brn",
	"V_Chestrig_khk",
	"V_TacVest_khk",
	"V_BandollierB_khk",
	"V_HarnessOGL_brn",
	"V_TacVest_brn",
	"V_PlateCarrier1_rgr",
	"V_Chestrig_rgr",
	"V_PlateCarrier2_rgr",
	"V_PlateCarrierSpec_rgr",
	"V_BandollierB_rgr",
	"V_PlateCarrierGL_rgr",
	// helmets
	"H_HelmetO_ocamo",
	"H_HelmetCrew_O",
	"H_HelmetLeaderO_ocamo",
	"H_Beret_ocamo",
	"H_MilCap_ocamo",
	"H_HelmetSpecO_ocamo",
	"H_HelmetSpecO_blk",
	"H_HelmetO_ViperSP_hex_F",
	"H_HelmetB_grass",
	"H_HelmetB_light",
	"H_HelmetB_light_desert",
	"H_HelmetCrew_B",
	"H_HelmetB_desert",
	"H_HelmetSpecB",
	"H_HelmetSpecB_blk",
	"H_HelmetB",
	"H_HelmetB_light_sand",
	"H_MilCap_mcamo",
	"H_HelmetB_sand",
	"H_HelmetB_camo",
	"H_HelmetB_snakeskin",
	"H_HelmetSpecB_sand",
	"H_HelmetB_light_grass",
	"H_HelmetSpecB_paint1",
	"H_HelmetB_light_snakeskin",
	"H_Booniehat_mcamo",
	"H_Watchcap_camo",
	"H_HelmetB_plain_mcamo",
	// backpacks
	"B_FieldPack_cbr_Ammo",
	"B_Carryall_ocamo_AAR",
	"O_HMG_01_support_F",
	"O_Mortar_01_support_F",
	"B_Carryall_cbr_AHAT",
	"B_Carryall_ocamo_AAA",
	"B_Carryall_cbr_AAT",
	"B_FieldPack_ocamo_Medic",
	"B_Carryall_ocamo_Eng",
	"B_Carryall_ocamo_Exp",
	"O_GMG_01_weapon_F",
	"O_HMG_01_weapon_F",
	"O_Mortar_01_weapon_F",
	"B_Carryall_ocamo_Mine",
	"B_FieldPack_ocamo_AA",
	"B_FieldPack_cbr_AT",
	"B_Parachute",
	"B_FieldPack_cbr_Repair",
	"B_FieldPack_cbr_LAT",
	"B_FieldPack_cbr_HAT",
	"O_UAV_01_backpack_F",
	"O_UAV_06_backpack_F",
	"O_UAV_06_medical_backpack_F",
	"B_FieldPack_ocamo_ReconExp",
	"B_FieldPack_ocamo_ReconMedic",
	"B_FieldPack_cbr_RPG_AT",
	"B_ViperHarness_hex_Exp_F",
	"B_ViperHarness_hex_JTAC_F",
	"B_ViperHarness_hex_M_F",
	"B_ViperHarness_hex_Medic_F",
	"B_ViperHarness_hex_LAT_F",
	"B_ViperHarness_hex_TL_F",
	"B_AssaultPack_mcamo_Ammo",
	"B_Kitbag_rgr_AAR",
	"B_HMG_01_support_F",
	"B_Mortar_01_support_F",
	"B_Carryall_mcamo_AAA",
	"B_Carryall_mcamo_AAT",
	"B_AssaultPack_rgr_Medic",
	"B_Kitbag_mcamo_Eng",
	"B_Kitbag_rgr_Exp",
	"B_GMG_01_weapon_F",
	"B_HMG_01_weapon_F",
	"B_Mortar_01_weapon_F",
	"B_Carryall_oli_Mine",
	"B_AssaultPack_mcamo_AA",
	"B_AssaultPack_mcamo_AT",
	"B_Parachute",
	"B_AssaultPack_rgr_Repair",
	"B_AssaultPack_rgr_LAT",
	"B_AssaultPack_rgr_LAT2",
	"B_UAV_01_backpack_F",
	"B_UAV_06_backpack_F",
	"B_UAV_06_medical_backpack_F",
	"B_UGV_02_Demining_backpack_F",
	"B_UGV_02_Science_backpack_F",
	"B_Patrol_Supply_bag_F",
	"B_Patrol_Medic_bag_F",
	"B_Patrol_Launcher_bag_F",
	"B_Patrol_Respawn_bag_F",
	"B_AssaultPack_rgr_ReconExp",
	"B_AssaultPack_rgr_ReconMedic",
	"B_AssaultPack_rgr_ReconLAT"
];

_desert = [
	//terrains
	"#GdtDirt",
	"#GdtSoil",
	"#GdtThorn",
	"#GdtGrassDry",
	"#GdtBeach",
	"#GdtConcrete",
	"#GdtDead",
	"#GdtMarsh",
	"#GdtDesert",
	"#GdtStratisBeach",
	//Takistan
	"#TKMoutain", //Loose, large stones. not a typo. Makes up the majority of Takistan's mountainous areas
	"#TKValouny", //Large irregular rocks and small stones, makes up most airbase surfaces
	"#TKTrava",	//dry grass, often interspersed with #TKValouny and #TKMoutain to form sparsely grassed areas
	"#TKSterkNaDno", //sandy terrain with loose rocks
	"#TKHlina", //Packed Rocky dirt
	"#TKPolopoust", //pebbly desert. Makes up the vast expanses outside the map.
	"#TKBeton", //Broken sand colored concrete, used for the northern airfield
	"#TKForest", //this is a dry khaki grass, makes up the floor of takistans sparse forest along with #TKTrava and #TKMoutain
	//Zargabad
	"#ZRHlina", //loose rocks and pepples.
	"#ZRDlazbaOld", //Sandy Cobblestone in Zargabad
	"#ZRBeton", //Broken sand colored concrete, used for theairfield
	"#ZRSterkNaDno", //sandy terrain with loose rocks, used for the river bottom
	"#ZRPolopoust", //pebbly desert. Makes up the vast expanses outside the map.
	"#ZRPlevel", //mowed straw colored grass
	//Sahrani
	"#AiA_Mud",
	"#sand",
	"#RockSouth",
	//Chernarus
	"#CRSterk",
	"#CRSSterk",
	"#CRSConcrete",
	"#CRConcrete",
	"#CRTarmac",
	"#CRSTarmac",
	//Uniform
	"CUP_U_B_CZ_DST_NoKneepads",
	"CUP_U_B_CZ_DST_Kneepads_Sleeve",
	"CUP_U_B_CZ_DST_TShirt",
	"CUP_U_B_CZ_Pilot_WDL",
	"CUP_U_B_CZ_DST_Ghillie",
	"CUP_U_O_RUS_BeigeDigital_MSV",
	"CUP_U_O_RUS_BeigeDigital_MSV_gloves_pads",
	"CUP_U_O_RUS_BeigeDigital_MSV_rolled_up",
	"CUP_U_O_RUS_BeigeDigital_MSV_rolled_up_gloves_pads",
	"CUP_U_O_RUS_BeigeDigital_VDV",
	"CUP_U_O_RUS_BeigeDigital_VDV_gloves_pads",
	"CUP_U_O_RUS_BeigeDigital_VDV_rolled_up",
	"CUP_U_O_RUS_BeigeDigital_VDV_rolled_up_gloves_pads",
	"CUP_U_O_RUS_KSOR_VDV",
	"CUP_U_O_RUS_KSOR_VDV_gloves_pads",
	"CUP_U_O_RUS_KSOR_VDV_rolled_up",
	"CUP_U_O_RUS_KSOR_VDV_rolled_up_gloves_pads",
	"CUP_U_B_BAF_MTP_GHILLIE",
	"CUP_U_B_BAF_DDPM_GHILLIE",
	"CUP_U_B_BAF_MTP_UBACSLONG",
	"CUP_U_B_BAF_MTP_UBACSSEAL",
	"CUP_U_B_BAF_MTP_UBACSLONGKNEE",
	"CUP_U_B_BAF_MTP_UBACSROLLED",
	"CUP_U_B_BAF_MTP_UBACSROLLEDKNEE",
	"CUP_U_B_BAF_MTP_UBACSTSHIRT",
	"CUP_U_B_BAF_MTP_UBACSTSHIRTKNEE",
	"CUP_U_B_BAF_DDPM_UBACSLONG_Gloves",
	"CUP_U_B_BAF_DDPM_UBACSLONGKNEE_Gloves",
	"CUP_U_B_BAF_DDPM_UBACSROLLED_Gloves",
	"CUP_U_B_BAF_DDPM_UBACSTSHIRT_Gloves",
	"CUP_U_B_BAF_MTP_UBACSLONG_Gloves",
	"CUP_U_B_BAF_MTP_UBACSLONGKNEE_Gloves",
	"CUP_U_B_BAF_MTP_UBACSROLLED_Gloves",
	"CUP_U_B_BAF_MTP_UBACSTSHIRT_Gloves",
	"CUP_U_B_BAF_DDPM_UBACSLONG",
	"CUP_U_B_BAF_DDPM_UBACSSEAL",
	"CUP_U_B_BAF_DDPM_UBACSLONGKNEE",
	"CUP_U_B_BAF_DDPM_UBACSROLLED",
	"CUP_U_B_BAF_DDPM_UBACSROLLEDKNEE",
	"CUP_U_B_BAF_DDPM_UBACSTSHIRT",
	"CUP_U_B_BAF_DDPM_UBACSTSHIRTKNEE",
	"CUP_U_B_BDUv2_DCU",
	"CUP_U_B_BDUv2_dirty_DCU",
	"CUP_U_B_BDUv2_gloves_DCU",
	"CUP_U_B_BDUv2_gloves_dirty_DCU",
	"CUP_U_B_BDUv2_roll2_DCU",
	"CUP_U_B_BDUv2_roll2_dirty_DCU",
	"CUP_U_B_BDUv2_roll2_gloves_DCU",
	"CUP_U_B_BDUv2_roll2_gloves_dirty_DCU",
	"CUP_U_B_BDUv2_roll_DCU",
	"CUP_U_B_BDUv2_roll_dirty_DCU",
	"CUP_U_B_BDUv2_roll_gloves_DCU",
	"CUP_U_B_BDUv2_roll_gloves_dirty_DCU",
	"CUP_U_B_BDUv2_DDPM",
	"CUP_U_B_BDUv2_dirty_DDPM",
	"CUP_U_B_BDUv2_gloves_DDPM",
	"CUP_U_B_BDUv2_gloves_dirty_DDPM",
	"CUP_U_B_BDUv2_roll2_DDPM",
	"CUP_U_B_BDUv2_roll2_dirty_DDPM",
	"CUP_U_B_BDUv2_roll2_gloves_DDPM",
	"CUP_U_B_BDUv2_roll2_gloves_dirty_DDPM",
	"CUP_U_B_BDUv2_roll_DDPM",
	"CUP_U_B_BDUv2_roll_dirty_DDPM",
	"CUP_U_B_BDUv2_roll_gloves_DDPM",
	"CUP_U_B_BDUv2_roll_gloves_dirty_DDPM",
	"CUP_U_B_BDUv2_desert",
	"CUP_U_B_BDUv2_dirty_desert",
	"CUP_U_B_BDUv2_gloves_desert",
	"CUP_U_B_BDUv2_gloves_dirty_desert",
	"CUP_U_B_BDUv2_roll2_desert",
	"CUP_U_B_BDUv2_roll2_dirty_desert",
	"CUP_U_B_BDUv2_roll2_gloves_desert",
	"CUP_U_B_BDUv2_roll2_gloves_dirty_desert",
	"CUP_U_B_BDUv2_roll_desert",
	"CUP_U_B_BDUv2_roll_dirty_desert",
	"CUP_U_B_BDUv2_roll_gloves_desert",
	"CUP_U_B_BDUv2_roll_gloves_dirty_desert",
	"CUP_U_B_CDF_DST_1",
	"CUP_U_B_CDF_DST_2",
	"CUP_U_CRYEG3_V1",
	"CUP_U_CRYEG3_V2",
	"CUP_U_CRYE_G3C_MC_US",
	"CUP_U_CRYE_G3C_MC_V2",
	"CUP_U_CRYE_G3C_MC_V3",
	"CUP_U_CRYE_G3C_MC",
	"CUP_U_CRYE_G3C_Tan_MC_US",
	"CUP_U_CRYE_G3C_MC_US_V2",
	"CUP_U_CRYE_MCAM_NP_Full",
	"CUP_U_CRYE_MCAM_NP_Roll",
	"CUP_U_CRYE_MCAM_RUS_Full",
	"CUP_U_CRYE_MCAM_RUS_Roll",
	"CUP_U_CRYE_MCAM_NP2_Full",
	"CUP_U_CRYE_MCAM_RUS2_Full",
	"CUP_U_CRYE_MCAM_RUS2_Roll",
	"CUP_U_CRYE_V2_Roll",
	"CUP_U_CRYE_V1_Full",
	"CUP_U_CRYE_V2_Full",
	"CUP_U_CRYE_V3_Full",
	"CUP_U_CRYE_V1_Roll",
	"CUP_U_CRYE_V3_Roll",
	"CUP_U_CRYE_TAN_Full",
	"CUP_U_CRYE_TAN_Roll",
	"CUP_U_CRYE_TAN_US_Full",
	"CUP_U_CRYE_TAN_US_Roll",
	"CUP_U_B_GER_Crye",
	"CUP_U_B_GER_Crye2",
	"CUP_U_B_GER_Overalls_Tank",
	"CUP_U_B_GER_Tropentarn_1",
	"CUP_U_B_GER_Tropentarn_2",
	"CUP_U_B_GER_Tropentarn_3",
	"CUP_U_B_GER_Tropentarn_4",
	"CUP_U_B_GER_Tropentarn_5",
	"CUP_U_B_GER_Tropentarn_6",
	"CUP_U_B_GER_Tropentarn_7",
	"CUP_U_B_GER_Tropentarn_8",
	"CUP_U_O_RUS_Ratnik_BeigeDigital",
	"CUP_U_O_RUS_Ratnik_Desert",
	"CUP_U_O_RUS_Ratnik_Pink",
	"CUP_U_O_ODKB_KSOR_VDV",
	"CUP_U_O_ODKB_KSOR_VDV_gloves_pads",
	"CUP_U_O_ODKB_KSOR_VDV_rolled_up",
	"CUP_U_O_ODKB_KSOR_VDV_rolled_up_gloves_pads",
	"CUP_U_B_USMC_PilotOverall",
	"CUP_I_B_PARA_Unit_5",
	"CUP_I_B_PARA_Unit_11",
	"CUP_I_B_PARA_Unit_13",
	"CUP_I_B_PARA_Unit_12",
	"CUP_I_B_PARA_Unit_15",
	"CUP_I_B_PARA_Unit_14",
	"CUP_I_B_PARA_Unit_8",
	"CUP_I_B_PARA_Unit_7",
	"CUP_I_B_PARA_Unit_10", //Pants take priority
	"CUP_I_B_PARA_Unit_3",
	"CUP_I_B_PARA_Unit_2",
	"CUP_I_B_PMC_Unit_35",
	"CUP_U_I_RACS_PilotOverall",
	"CUP_U_I_RACS_Desert_1",
	"CUP_U_I_RACS_Desert_2",
	"CUP_U_O_SLA_Desert",
	"CUP_U_O_TK_Ghillie_Top",
	"CUP_U_O_TK_MixedCamo",
	"CUP_U_O_RUS_M88_MSV",
	"CUP_U_O_RUS_M88_MSV_rolled_up",
	"CUP_U_O_RUS_M88_VDV",
	"CUP_U_O_RUS_M88_VDV_rolled_up",
	"CUP_U_B_USArmy_TwoKnee",
	"CUP_U_B_USArmy_Base",
	"CUP_U_B_USArmy_Soft",
	"CUP_U_B_USArmy_UBACS",
	"CUP_U_B_USArmy_ACU_Gloves_OCP",
	"CUP_U_B_USArmy_ACU_Gloves_OEFCP",
	"CUP_U_B_USArmy_ACU_Gloves_UCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Gloves_OCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Gloves_OEFCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Gloves_UCP",
	"CUP_U_B_USArmy_ACU_Kneepad_OCP",
	"CUP_U_B_USArmy_ACU_Kneepad_OEFCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Rolled_Gloves_OCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Rolled_Gloves_OEFCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Rolled_Gloves_UCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Rolled_OCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Rolled_OEFCP",
	"CUP_U_B_USArmy_ACU_Kneepad_Rolled_UCP",
	"CUP_U_B_USArmy_ACU_Kneepad_UCP",
	"CUP_U_B_USArmy_ACU_OCP",
	"CUP_U_B_USArmy_ACU_OEFCP",
	"CUP_U_B_USArmy_ACU_Rolled_Gloves_OCP",
	"CUP_U_B_USArmy_ACU_Rolled_Gloves_OEFCP",
	"CUP_U_B_USArmy_ACU_Rolled_Gloves_UCP",
	"CUP_U_B_USArmy_ACU_Rolled_OCP",
	"CUP_U_B_USArmy_ACU_Rolled_OEFCP",
	"CUP_U_B_USArmy_ACU_Rolled_UCP",
	"CUP_U_B_USArmy_ACU_UCP",
	"CUP_U_B_BDUv2_DCU_US",
	"CUP_U_B_BDUv2_dirty_DCU_US",
	"CUP_U_B_BDUv2_gloves_DCU_US",
	"CUP_U_B_BDUv2_gloves_dirty_DCU_US",
	"CUP_U_B_BDUv2_roll2_DCU_US",
	"CUP_U_B_BDUv2_roll2_dirty_DCU_US",
	"CUP_U_B_BDUv2_roll2_gloves_DCU_US",
	"CUP_U_B_BDUv2_roll2_gloves_dirty_DCU_US",
	"CUP_U_B_BDUv2_roll_DCU_US",
	"CUP_U_B_BDUv2_roll_dirty_DCU_US",
	"CUP_U_B_BDUv2_roll_gloves_DCU_US",
	"CUP_U_B_BDUv2_roll_gloves_dirty_DCU_US",
	"CUP_U_B_BDUv2_desert_US",
	"CUP_U_B_BDUv2_dirty_desert_US",
	"CUP_U_B_BDUv2_gloves_desert_US",
	"CUP_U_B_BDUv2_gloves_dirty_desert_US",
	"CUP_U_B_BDUv2_roll2_desert_US",
	"CUP_U_B_BDUv2_roll2_dirty_desert_US",
	"CUP_U_B_BDUv2_roll2_gloves_desert_US",
	"CUP_U_B_BDUv2_roll2_gloves_dirty_desert_US",
	"CUP_U_B_BDUv2_roll_desert_US",
	"CUP_U_B_BDUv2_roll_dirty_desert_US",
	"CUP_U_B_BDUv2_roll_gloves_desert_US",
	"CUP_U_B_BDUv2_roll_gloves_dirty_desert_US",
	"CUP_U_B_USMC_FROG1_DMARPAT",
	"CUP_U_B_USMC_FROG2_DMARPAT",
	"CUP_U_B_USMC_FROG3_DMARPAT",
	"CUP_U_B_USMC_FROG4_DMARPAT",
	"CUP_U_B_USMC_MCCUU_des_gloves",
	"CUP_U_B_USMC_MCCUU_des_roll_2",
	"CUP_U_B_USMC_MCCUU_des_roll_2_gloves",
	"CUP_U_B_USMC_MCCUU_des_roll_2_pads",
	"CUP_U_B_USMC_MCCUU_des_roll_2_pads_gloves",
	"CUP_U_B_USMC_MCCUU_des_pads",
	"CUP_U_B_USMC_MCCUU_des_pads_gloves",
	"CUP_U_B_USMC_MCCUU_des_roll",
	"CUP_U_B_USMC_MCCUU_des_roll_gloves",
	"CUP_U_B_USMC_MCCUU_des_roll_pads",
	"CUP_U_B_USMC_MCCUU_des_roll_pads_gloves",
	//Vest
	"CUP_V_O_SLA_6B3_1_DES",
	"CUP_V_O_SLA_6B3_2_DES",
	"CUP_V_O_SLA_6B3_3_DES",
	"CUP_V_O_SLA_6B3_4_DES",
	"CUP_V_O_SLA_6B3_5_DES",
	"CUP_V_O_SLA_M23_1_BRN",
	"CUP_V_RUS_6B45_1_BeigeDigital",
	"CUP_V_RUS_6B45_2_BeigeDigital",
	"CUP_V_RUS_6B45_3_BeigeDigital",
	"CUP_V_RUS_6B45_4_BeigeDigital",
	"CUP_Vest_RUS_6B45_Sh117_BeigeDigital",
	"CUP_Vest_RUS_6B45_Sh117_PKP_BeigeDigital",
	"CUP_Vest_RUS_6B45_Sh117_VOG_BeigeDigital",
	"CUP_Vest_RUS_6B45_Sh117_Desert",
	"CUP_Vest_RUS_6B45_Sh117_PKP_Desert",
	"CUP_Vest_RUS_6B45_Sh117_VOG_Desert",
	"CUP_V_CZ_NPP2006_des",
	"CUP_V_CZ_NPP2006_nk_des",
	"CUP_V_CZ_NPP2006_ok_des",
	"CUP_V_CZ_NPP2006_co_des",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Empty",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_AutomaticRifleman",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Crewman",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Engineer",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Grenadier",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Medic",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Officer",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Pilot",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Rifleman",
	"CUP_V_B_BAF_DDPM_Osprey_Mk3_Scout",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Empty",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_AutomaticRifleman",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Crewman",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Engineer",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Grenadier",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Medic",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Officer",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Rifleman",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Scout",
	"CUP_V_I_RACS_Carrier_Vest",
	"CUP_V_I_RACS_Carrier_Vest_2",
	"CUP_V_I_RACS_Carrier_Vest_3",
	"CUP_V_CDF_6B3_1_DST",
	"CUP_V_CDF_6B3_2_DST",
	"CUP_V_CDF_6B3_4_DST",
	"CUP_V_CDF_6B3_3_DST",
	"CUP_V_CDF_6B3_5_DST",
	"CUP_V_B_Ciras_Coyote",
	"CUP_V_B_Ciras_Coyote2",
	"CUP_V_B_Ciras_Coyote3",
	"CUP_V_B_Ciras_Coyote4",
	"CUP_V_B_Ciras_Coyote_USSF",
	"CUP_V_B_Ciras_Khaki",
	"CUP_V_B_Ciras_Khaki2",
	"CUP_V_B_Ciras_Khaki3",
	"CUP_V_B_Ciras_Khaki4",
	"CUP_V_B_Ciras_MCam",
	"CUP_V_B_Ciras_MCam2",
	"CUP_V_B_Ciras_Mcam3",
	"CUP_V_B_Ciras_Mcam4",
	"CUP_V_PMC_CIRAS_Coyote_Patrol_Marsoc1",
	"CUP_V_PMC_CIRAS_Coyote_Patrol_Marsoc2",
	"CUP_V_PMC_CIRAS_Coyote_Veh",
	"CUP_V_PMC_CIRAS_Coyote_Empty",
	"CUP_V_PMC_CIRAS_Coyote_Grenadier",
	"CUP_V_PMC_CIRAS_Coyote_Patrol",
	"CUP_V_PMC_CIRAS_Coyote_TL",
	"CUP_V_CPC_communications_coy",
	"CUP_V_CPC_Fast_coy",
	"CUP_V_CPC_light_coy",
	"CUP_V_CPC_medical_coy",
	"CUP_V_CPC_tl_coy",
	"CUP_V_CPC_weapons_coy",
	"CUP_V_CPC_communicationsbelt_coy",
	"CUP_V_CPC_Fastbelt_coy",
	"CUP_V_CPC_lightbelt_coy",
	"CUP_V_CPC_medicalbelt_coy",
	"CUP_V_CPC_tlbelt_coy",
	"CUP_V_CPC_weaponsbelt_coy",
	"CUP_V_CPC_communications_mc",
	"CUP_V_CPC_Fast_mc",
	"CUP_V_CPC_light_mc",
	"CUP_V_CPC_medical_mc",
	"CUP_V_CPC_tl_mc",
	"CUP_V_CPC_weapons_mc",
	"CUP_V_CPC_communicationsbelt_mc",
	"CUP_V_CPC_Fastbelt_mc",
	"CUP_V_CPC_lightbelt_mc",
	"CUP_V_CPC_medicalbelt_mc",
	"CUP_V_CPC_tlbelt_mc",
	"CUP_V_CPC_weaponsbelt_mc",
	"CUP_V_B_Armatus_Coyote",
	"CUP_V_B_Armatus_BB_Coyote",
	"CUP_V_B_GER_Armatus_Trop",
	"CUP_V_B_GER_Armatus_BB_Trop",
	"CUP_V_B_JPC_Trop_Light",
	"CUP_V_B_LBT_LBV_Coyote",
	"CUP_V_B_LBT_LBV_MCam",
	"CUP_V_B_GER_Carrier_Vest_2",
	"CUP_V_B_GER_Carrier_Rig_2_Brown",
	"CUP_V_B_GER_Carrier_Rig_3_Brown",
	"CUP_V_B_GER_PVest_Trop_Gren",
	"CUP_V_B_GER_PVest_Trop_Gren_LT",
	"CUP_V_B_GER_PVest_Trop_MG",
	"CUP_V_B_GER_PVest_Trop_MG_LT",
	"CUP_V_B_GER_PVest_Trop_Med",
	"CUP_V_B_GER_PVest_Trop_Med_LT",
	"CUP_V_B_GER_PVest_Trop_OFC",
	"CUP_V_B_GER_PVest_Trop_RFL",
	"CUP_V_B_GER_PVest_Trop_RFL_LT",
	"CUP_V_B_GER_PVest_Trop_TL",
	"CUP_V_B_GER_PVest_Trop_TL_LT",
	"CUP_V_B_GER_Tactical_Trop",
	"CUP_V_B_Interceptor_Base_Coyote",
	"CUP_V_B_Interceptor_Grenadier_Coyote",
	"CUP_V_B_Interceptor_Rifleman_Coyote",
	"CUP_V_B_Interceptor_Base_DCU",
	"CUP_V_B_Interceptor_Grenadier_DCU",
	"CUP_V_B_Interceptor_Rifleman_DCU",
	"CUP_V_B_IOTV_OCP_Empty_USArmy",
	"CUP_V_B_IOTV_OEFCP_Empty_USArmy",
	"CUP_V_B_IOTV_UCP_Empty_USArmy",
	"CUP_V_B_IOTV_OCP_Grenadier_USArmy",
	"CUP_V_B_IOTV_OEFCP_Grenadier_USArmy",
	"CUP_V_B_IOTV_UCP_Grenadier_USArmy",
	"CUP_V_B_IOTV_OCP_MG_USArmy",
	"CUP_V_B_IOTV_OEFCP_MG_USArmy",
	"CUP_V_B_IOTV_UCP_MG_USArmy",
	"CUP_V_B_IOTV_OCP_Medic_USArmy",
	"CUP_V_B_IOTV_OEFCP_Medic_USArmy",
	"CUP_V_B_IOTV_UCP_Medic_USArmy",
	"CUP_V_B_IOTV_OCP_Rifleman_Deltoid_USArmy",
	"CUP_V_B_IOTV_OEFCP_Rifleman_Deltoid_USArmy",
	"CUP_V_B_IOTV_UCP_Rifleman_Deltoid_USArmy",
	"CUP_V_B_IOTV_OCP_Rifleman_USArmy",
	"CUP_V_B_IOTV_OEFCP_Rifleman_USArmy",
	"CUP_V_B_IOTV_UCP_Rifleman_USArmy",
	"CUP_V_B_IOTV_OCP_SAW_USArmy",
	"CUP_V_B_IOTV_OEFCP_SAW_USArmy",
	"CUP_V_B_IOTV_UCP_SAW_USArmy",
	"CUP_V_B_IOTV_OCP_SL_USArmy",
	"CUP_V_B_IOTV_OEFCP_SL_USArmy",
	"CUP_V_B_IOTV_UCP_SL_USArmy",
	"CUP_V_B_IOTV_OCP_TL_USArmy",
	"CUP_V_B_IOTV_OEFCP_TL_USArmy",
	"CUP_V_B_IOTV_UCP_TL_USArmy",
	"CUP_V_PMC_IOTV_Coyote_AR",
	"CUP_V_PMC_IOTV_Coyote_Empty",
	"CUP_V_PMC_IOTV_Coyote_Gren",
	"CUP_V_PMC_IOTV_Coyote_Patrol",
	"CUP_V_PMC_IOTV_Coyote_TL",
	"CUP_V_JPC_communications_coy",
	"CUP_V_JPC_Fast_coy",
	"CUP_V_B_JPC_Tan_Light",
	"CUP_V_JPC_medical_coy",
	"CUP_V_JPC_tl_coy",
	"CUP_V_JPC_weapons_coy",
	"CUP_V_JPC_communicationsbelt_coy",
	"CUP_V_JPC_Fastbelt_coy",
	"CUP_V_JPC_lightbelt_coy",
	"CUP_V_JPC_medicalbelt_coy",
	"CUP_V_JPC_tlbelt_coy",
	"CUP_V_JPC_weaponsbelt_coy",
	"CUP_V_B_JPC_MCam_Light",
	"CUP_V_JPC_communications_mc",
	"CUP_V_JPC_Fast_mc",
	"CUP_V_JPC_medical_mc",
	"CUP_V_JPC_tl_mc",
	"CUP_V_JPC_weapons_mc",
	"CUP_V_JPC_communicationsbelt_mc",
	"CUP_V_JPC_Fastbelt_mc",
	"CUP_V_JPC_lightbelt_mc",
	"CUP_V_JPC_medicalbelt_mc",
	"CUP_V_JPC_tlbelt_mc",
	"CUP_V_JPC_weaponsbelt_mc",
	"CUP_V_MBSS_PACA_CB",
	"CUP_V_MBSS_PACA2_CB",
	"CUP_V_MBSS_PACA_Tan",
	"CUP_V_MBSS_PACA2_Tan",
	"CUP_V_O_TK_Vest_1",
	"CUP_V_O_TK_Vest_2",
	"CUP_V_I_RACS_Carrier_Rig_2",
	"CUP_V_I_RACS_Carrier_Rig_3",
	"CUP_V_B_MTV_Pouches",
	"CUP_V_B_MTV_PistolBlack",
	"CUP_V_B_MTV",
	"CUP_V_B_MTV_Mine",
	"CUP_V_B_MTV_LegPouch",
	"CUP_V_B_MTV_Marksman",
	"CUP_V_B_MTV_MG",
	"CUP_V_B_MTV_Patrol",
	"CUP_V_B_MTV_noCB",
	"CUP_V_B_MTV_TL",
	"CUP_V_B_PASGT_desert",
	"CUP_V_B_PASGT_no_bags_desert",
	"CUP_V_B_RRV_Light_CB",
	"CUP_V_B_RRV_MG",
	"CUP_V_B_RRV_Medic_CB",
	"CUP_V_B_RRV_Officer_CB",
	"CUP_V_B_RRV_Scout_CB",
	"CUP_V_B_RRV_Scout2_CB",
	"CUP_V_B_RRV_Scout3",
	"CUP_V_B_RRV_TL_CB",
	"CUP_V_B_Eagle_SPC_AT",
	"CUP_V_B_Eagle_SPC_AR",
	"CUP_V_B_Eagle_SPC_Corpsman",
	"CUP_V_B_Eagle_SPC_Crew",
	"CUP_V_B_Eagle_SPC_Empty",
	"CUP_V_B_Eagle_SPC_GL",
	"CUP_V_B_Eagle_SPC_MG",
	"CUP_V_B_Eagle_SPC_DMR",
	"CUP_V_B_Eagle_SPC_Officer",
	"CUP_V_B_Eagle_SPC_Patrol",
	"CUP_V_B_Eagle_SPC_RTO",
	"CUP_V_B_Eagle_SPC_Rifleman",
	"CUP_V_B_Eagle_SPC_Scout",
	"CUP_V_B_Eagle_SPC_SL",
	"CUP_V_B_Eagle_SPC_TL",
	"CUP_V_OI_TKI_Jacket1_01",
	"CUP_V_OI_TKI_Jacket4_02",
	"CUP_V_OI_TKI_Jacket4_03",
	"CUP_V_OI_TKI_Jacket5_03",
	"CUP_V_OI_TKI_Jacket3_02",
	"CUP_V_OI_TKI_Jacket6_02",
	"CUP_V_OI_TKI_Jacket6_03",
	"CUP_V_OI_TKI_Jacket2_03",
	"CUP_V_B_USArmy_PilotVest",
	"CUP_V_B_Armatus_US_MCam",
	"CUP_V_B_Armatus_BB_US_MCam",
	"CUP_V_B_Armatus_MCam",
	"CUP_V_B_Armatus_BB_MCam",
	"CUP_V_B_LBT_LBV_US_MCam",
	//Hat
	"CUP_H_RUS_6B27_cover_BeigeDigital",
	"CUP_H_RUS_6B27_cover_BeigeDigital_goggles",
	"CUP_H_RUS_6B27_cover_BeigeDigital_headset_goggles",
	"CUP_H_RUS_6B27_cover_BeigeDigital_headset",
	"CUP_H_RUS_6B47_v2_BeigeDigital",
	"CUP_H_RUS_6B47_v2_GogglesClosed_BeigeDigital",
	"CUP_H_RUS_6B47_v2_GogglesDown_BeigeDigital",
	"CUP_H_RUS_6B47_v2_GogglesUp_BeigeDigital",
	"CUP_H_RUS_6B47_v2_Desert",
	"CUP_H_RUS_6B47_v2_GogglesClosed_Desert",
	"CUP_H_RUS_6B47_v2_GogglesDown_Desert",
	"CUP_H_RUS_6B47_v2_GogglesUp_Desert",
	"CUP_H_RUS_6B47_desert",
	"CUP_H_RUS_6B47_goggles_desert",
	"CUP_H_RUS_6B47_headset_goggles_desert",
	"CUP_H_RUS_6B47_headset_desert",
	"CUP_H_RUS_6B47_SF_headset_goggles_desert",
	"CUP_H_RUS_6B47_SF_headset_desert",
	"CUP_H_USArmy_HelmetACH_OCP",
	"CUP_H_USArmy_HelmetACH_GCOVERED_OCP",
	"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_OCP",
	"CUP_H_USArmy_HelmetACH_ESS_OCP",
	"CUP_H_USArmy_HelmetACH_ESS_Headset_OCP",
	"CUP_H_USArmy_HelmetACH_Headset_OCP",
	"CUP_H_USArmy_HelmetACH_OEFCP",
	"CUP_H_USArmy_HelmetACH_GCOVERED_OEFCP",
	"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_OEFCP",
	"CUP_H_USArmy_HelmetACH_ESS_OEFCP",
	"CUP_H_USArmy_HelmetACH_ESS_Headset_OEFCP",
	"CUP_H_USArmy_HelmetACH_Headset_OEFCP",
	"CUP_H_USArmy_HelmetACH_UCP",
	"CUP_H_USArmy_HelmetACH_GCOVERED_UCP",
	"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_UCP",
	"CUP_H_USArmy_HelmetACH_ESS_UCP",
	"CUP_H_USArmy_HelmetACH_ESS_Headset_UCP",
	"CUP_H_USArmy_HelmetACH_Headset_UCP",
	"CUP_H_USMC_BOONIE_2_DES",
	"CUP_H_CZ_Booniehat_fold_des",
	"CUP_H_Ger_Boonie2_desert",
	"CUP_H_Ger_Boonie_desert",
	"CUP_H_FR_Boonie_DES",
	"CUP_H_USMC_BOONIE_PRR_DES",
	"CUP_H_USArmy_Boonie_hs_OCP",
	"CUP_H_USArmy_Boonie_hs_OEFCP",
	"CUP_H_USArmy_Boonie_hs_UCP",
	"CUP_H_USArmy_Boonie_OCP",
	"CUP_H_USArmy_Boonie_OEFCP",
	"CUP_H_SLA_Boonie_DES",
	"CUP_H_USArmy_Boonie_UCP",
	"CUP_H_RUS_Cap_ATACSAU",
	"CUP_H_USA_Cap_MCAM",
	"CUP_H_PMC_Cap_Tan",
	"CUP_H_CZ_Cap_khk",
	"CUP_H_CZ_Cap_Headphones_des",
	"CUP_H_CZ_Hat04",
	"CUP_H_Ger_Cap_EP_Tan2",
	"CUP_H_Ger_Cap_EP_Tan1",
	"CUP_H_Ger_Cap_Tan2",
	"CUP_H_Ger_Cap_Tan1",
	"CUP_H_USA_Cap_TREAD_DEF",
	"CUP_H_USA_Cap_MARSOC_DEF",
	"CUP_H_USA_Cap_Mcam_DEF",
	"CUP_H_PMC_Cap_Back_Tan",
	"CUP_H_PMC_Cap_Back_EP_Tan",
	"CUP_H_PMC_Cap_Back_PRR_Tan",
	"CUP_H_PMC_Cap_EP_Tan",
	"CUP_H_PMC_Cap_PRR_Tan",
	"CUP_H_CZ_Helmet01",
	"CUP_H_CZ_Helmet02",
	"CUP_H_CVCH_des",
	"CUP_H_USArmy_ECH_MARPAT_des",
	"CUP_H_USArmy_ECH_GCOVEREDMARPAT_des",
	"CUP_H_USArmy_ECH_GCOVERED_Headset_MARPAT_des",
	"CUP_H_USArmy_ECH_ESS_MARPAT_des",
	"CUP_H_USArmy_ECH_ESS_Headset_MARPAT_des",
	"CUP_H_USArmy_ECH_Headset_MARPAT_des",
	"CUP_H_USArmy_Helmet_ECH2_Sand",
	"CUP_H_FR_ECH",
	"CUP_H_USArmy_Helmet_ECH1_Sand",
	"CUP_H_LWHv2_brown",
	"CUP_H_LWHv2_brown_comms",
	"CUP_H_LWHv2_brown_ess_comms",
	"CUP_H_LWHv2_desert",
	"CUP_H_LWHv2_desert_comms",
	"CUP_H_LWHv2_desert_ess_comms",
	"CUP_H_LWHv2_MARPAT_des",
	"CUP_H_LWHv2_MARPAT_des_comms",
	"CUP_H_LWHv2_MARPAT_des_NVG_gog_cov2",
	"CUP_H_LWHv2_MARPAT_des_NVG_gog2_cov2",
	"CUP_H_LWHv2_MARPAT_des_cov_fr",
	"CUP_H_LWHv2_MARPAT_des_comms_cov_fr",
	"CUP_H_Ger_M92_Tan",
	"CUP_H_Ger_M92_Tan_GG",
	"CUP_H_Ger_M92_Tan_GG_CB",
	"CUP_H_Ger_M92_Tan_GG_CF",
	"CUP_H_Ger_M92_Cover_Trop",
	"CUP_H_Ger_M92_Cover_Trop_GG_CB",
	"CUP_H_Ger_M92_Cover_Trop_GG_CF",
	"CUP_H_Ger_M92_Cover_Trop_GG",
	"CUP_H_USArmy_MICH_UCP",
	"CUP_H_USArmy_MICH_GCOVERED_UCP",
	"CUP_H_USArmy_MICH_GCOVERED_Headset_UCP",
	"CUP_H_USArmy_MICH_ESS_UCP",
	"CUP_H_USArmy_MICH_ESS_Headset_UCP",
	"CUP_H_USArmy_MICH_Headset_UCP",
	"CUP_H_CZ_Helmet07",
	"CUP_H_CZ_Helmet08",
	"CUP_H_BAF_DDPM_Mk6_EMPTY",
	"CUP_H_BAF_DDPM_Mk6_EMPTY_PRR",
	"CUP_H_BAF_DDPM_Mk6_CREW_PRR",
	"CUP_H_BAF_DDPM_Mk6_GLASS_PRR",
	"CUP_H_BAF_DDPM_Mk6_GOGGLES_PRR",
	"CUP_H_BAF_DDPM_Mk6_NETTING_PRR",
	"CUP_H_BAF_MTP_Mk6_EMPTY",
	"CUP_H_BAF_MTP_Mk7",
	"CUP_H_BAF_MTP_Mk6_CREW_PRR",
	"CUP_H_BAF_MTP_Mk7_PRR_SCRIM_A",
	"CUP_H_BAF_MTP_Mk7_PRR_SCRIM_B",
	"CUP_H_BAF_MTP_Mk6_EMPTY_PRR",
	"CUP_H_BAF_MTP_Mk7_PRR",
	"CUP_H_BAF_MTP_Mk6_GLASS_PRR",
	"CUP_H_BAF_MTP_Mk6_GOGGLES_PRR",
	"CUP_H_BAF_MTP_Mk6_NETTING_PRR",
	"CUP_H_USMC_CAP_DES",
	"CUP_H_CDF_OfficerCap_DST",
	"CUP_H_OpsCore_Covered_Tropen",
	"CUP_H_OpsCore_Covered_Tropen_NoHS",
	"CUP_H_OpsCore_Covered_MTP",
	"CUP_H_OpsCore_Covered_MTP_NoHS",
	"CUP_H_OpsCore_Covered_MCAM_US",
	"CUP_H_OpsCore_Covered_MCAM",
	"CUP_H_OpsCore_Covered_MCAM_NoHS",
	"CUP_H_OpsCore_Spray_US",
	"CUP_H_OpsCore_Spray",
	"CUP_H_OpsCore_Spray_NoHS",
	"CUP_H_OpsCore_Tan",
	"CUP_H_OpsCore_Tan_NoHS",
	"CUP_H_OpsCore_Covered_UCP",
	"CUP_H_OpsCore_Covered_UCP_NoHS",
	"CUP_H_OpsCore_Covered_MTP_SF",
	"CUP_H_OpsCore_Covered_MCAM_US_SF",
	"CUP_H_OpsCore_Covered_MCAM_SF",
	"CUP_H_OpsCore_Spray_US_SF",
	"CUP_H_OpsCore_Spray_SF",
	"CUP_H_OpsCore_Tan_SF",
	"CUP_H_OpsCore_Covered_UCP_SF",
	"CUP_H_CDF_H_PASGT_DST",
	"CUP_H_CDF_H_PASGT_DST",
	"CUP_H_PASGTv2_desert",
	"CUP_H_PASGTv2_NVG_desert",
	"CUP_H_US_patrol_cap_DCU",
	"CUP_H_US_patrol_cap_desert",
	"CUP_H_US_patrol_cap_OCP",
	"CUP_H_US_patrol_cap_OEFCP",
	"CUP_H_US_patrol_cap_UCP",
	"CUP_H_SPH4_khaki",
	"CUP_H_SPH4_khaki_visor",
	"CUP_H_SLA_Helmet_DES",
	"CUP_H_SLA_Helmet_DES_worn",
	"CUP_H_TK_TankerHelmet"
];

_urban = [
	//terrains
	"#CityGround",
	"#IBRwintheratownSurface",
	"#IBRwintherasandSurface",
	//Takistan
	"#TKAsfalt", //sun bleached pale grey broken asphalt, used for building foundations and runway surfaces
	// uniforms
	"U_O_CombatUniform_oucamo",
	// vests
	"V_HarnessO_gry",
	"V_TacVest_blk",
	"V_HarnessOGL_gry",
	// helmets
	"H_HelmetO_oucamo",
	"H_HelmetLeaderO_oucamo",
	// backpacks
	"B_FieldPack_oucamo_Ammo",
	"B_Carryall_oucamo_AAR",
	"B_Carryall_oucamo_AAA",
	"B_Carryall_oucamo_AAT",
	"B_FieldPack_oucamo_Medic",
	"B_Carryall_oucamo_Eng",
	"B_Carryall_oucamo_Exp",
	"B_FieldPack_oucamo_AA",
	"B_FieldPack_oucamo_AT",
	"B_FieldPack_oucamo_Repair",
	"B_FieldPack_oucamo_LAT"
];

_snow = [
	//terrains
	"#ForestLeaves",
	"#RockNorth",
	"#WCGrass1",
	"#WCGrass2",
	"#WCSterk",
	"#WCHlina",
	"#WCField1",
	"#WCField2",
	"#WCHeather",
	"#WCForest1",
	"#WCForest2",
	"#WCTarmac",
	"#WCConcrete",
	"#IBRwintherasnowSurface",
	"#IBRwintherawoodSurface",
	"#IBRwintherasandSurface",
	//uniforms
	"CUP_U_B_BDUv2_M81_Winter", //WINTER ALWAYS TAKE PRIORITY _units will naturally avoid it like the plague unless it's winter
	"CUP_U_B_BDUv2_dirty_M81_Winter",
	"CUP_U_B_BDUv2_gloves_M81_Winter",
	"CUP_U_B_BDUv2_gloves_dirty_M81_Winter",
	"CUP_U_B_BDUv2_Winter",
	"CUP_U_B_BDUv2_dirty_Winter",
	"CUP_U_B_BDUv2_gloves_Winter",
	"CUP_U_B_BDUv2_gloves_dirty_Winter",
	"CUP_U_B_BDUv2_Winter_M81",
	"CUP_U_B_BDUv2_dirty_Winter_M81",
	"CUP_U_B_BDUv2_gloves_Winter_M81",
	"CUP_U_B_BDUv2_gloves_dirty_Winter_M81",
	"CUP_U_B_CDF_SNW_1",
	"CUP_U_B_CDF_SNW_2",
	"CUP_U_O_CHDKZ_Bardak",
	"CUP_U_O_CHDKZ_Kam_01",
	"CUP_U_O_CHDKZ_Kam_03",
	"CUP_U_O_CHDKZ_Commander",
	"CUP_U_O_CHDKZ_Kam_08",
	"CUP_U_O_CHDKZ_Kam_07",
	"CUP_I_B_PMC_Unit_28",
	"CUP_I_B_PMC_Unit_29",
	"CUP_I_B_PMC_Unit_26",
	"CUP_I_B_PMC_Unit_30",
	"CUP_I_B_PMC_Unit_27",
	"CUP_I_B_PMC_Unit_25",
	"CUP_I_B_PMC_Unit_34",
	"CUP_I_B_PMC_Unit_18",
	"CUP_I_B_PMC_Unit_33",
	"CUP_U_O_SLA_Urban",
	"CUP_U_O_RUS_Ratnik_Winter",
	//Vests
	"CUP_V_O_SLA_6B3_1_URB",
	"CUP_V_O_SLA_6B3_2_URB",
	"CUP_V_O_SLA_6B3_3_URB",
	"CUP_V_O_SLA_6B3_4_URB",
	"CUP_V_O_SLA_6B3_5_URB",
	"CUP_V_CDF_6B3_1_SNW",
	"CUP_V_CDF_6B3_2_SNW",
	"CUP_V_CDF_6B3_4_SNW",
	"CUP_V_CDF_6B3_3_SNW",
	"CUP_V_CDF_6B3_5_SNW",
	"CUP_V_PMC_CIRAS_Winter_Veh",
	"CUP_V_PMC_CIRAS_Winter_Empty",
	"CUP_V_PMC_CIRAS_Winter_Grenadier",
	"CUP_V_PMC_CIRAS_Winter_Patrol",
	"CUP_V_PMC_CIRAS_Winter_TL",
	"CUP_V_B_PASGT_winter",
	"CUP_V_B_PASGT_no_bags_winter",
	"CUP_V_OI_TKI_Jacket1_02",
	//Hats
	"CUP_H_RUS_6B47_v2_Winter",
	"CUP_H_RUS_6B47_v2_GogglesClosed_Winter",
	"CUP_H_RUS_6B47_v2_GogglesDown_Winter",
	"CUP_H_RUS_6B47_v2_GogglesUp_Winter",
	"CUP_H_RUS_Balaclava_Ratnik_Headphones_winter",
	"CUP_H_RUS_Balaclava_Ratnik_Headphones_winter_v2",
	"CUP_H_PMC_Beanie_Winter",
	"CUP_H_PMC_Beanie_Headphones_Winter",
	"CUP_H_SLA_Boonie_URB",
	"CUP_H_CDF_OfficerCap_SNW",
	"CUP_H_CDF_H_PASGT_SNW",
	"CUP_H_PASGTv2_NVG_winter",
	"CUP_H_PASGTv2_winter",
	"CUP_H_US_patrol_cap_winter"
];

_trans = [ //array for vest which the system should consider "transparant" and thus apply the camo type of the unifom worn underneath
	"",
	"V_Rangemaster_belt",
	"V_BandollierB_blk",
	"V_BandollierB_cbr",
	"V_BandollierB_ghex_F",
	"V_BandollierB_rgr",
	"V_BandollierB_khk",
	"V_BandollierB_oli",
	"CUP_V_CDF_OfficerBelt2",
	"CUP_V_CDF_OfficerBelt",
	"CUP_V_CDF_CrewBelt",
	"CUP_V_O_TK_CrewBelt",
	"CUP_V_O_TK_OfficerBelt2",
	"CUP_V_I_Carrier_Belt",
	"CUP_V_O_SLA_Carrier_Belt",
	"CUP_V_O_SLA_Carrier_Belt03",
	"CUP_V_O_SLA_Carrier_Belt02",
	"CUP_V_B_ALICE",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Belt",
	"CUP_V_B_BAF_MTP_Osprey_Mk4_Webbing",
	"CUP_V_O_Ins_Carrier_Rig_Com",
	"CUP_V_O_Ins_Carrier_Rig_Light",
	"CUP_V_O_Ins_Carrier_Rig_MG",
	"CUP_V_O_Ins_Carrier_Rig",
	"CUP_V_C_Police_Holster",
	"CUP_V_B_RRV_TL",
	"CUP_V_RUS_Smersh_2"
];

_ghillie = [
	"U_O_GhillieSuit",
	"U_O_FullGhillie_ard",
	"U_O_FullGhillie_lsh",
	"U_O_FullGhillie_sard",
	"U_O_T_Sniper_F",
	"U_O_T_FullGhillie_tna_F",
	"U_B_GhillieSuit",
	"U_B_FullGhillie_ard",
	"U_B_FullGhillie_lsh",
	"U_B_FullGhillie_sard",
	"U_B_T_Sniper_F",
	"U_B_T_FullGhillie_tna_F"
];

//Edited Killzone Kid's inHouse function that not only gets if the player is in cover but also how big that cover is
KK_fnc_inHouse = {
  _house = objNull;
  lineIntersectsSurfaces [
    getPosWorld _this,
    getPosWorld _this vectorAdd [0, 0, 50],
    _this, objNull, true, 1, "GEOM", "NONE"
  ] select 0 params ["","","","_house"];
  if (_house isKindOf "House") exitWith {
    _size = selectMax (boundingBox _house select 1);
    [true,_size]};
  [false,3]
};

_debug = 0;

_uniVal = 0.8;
_webVal = 0.85;
_hatVal = 0.9;

_camoFnc = {
	params ["_unit"];

	_camoIndex = 1.2;

	//Terrain Handling

	_mat = surfaceType position _unit;

	_uni = uniform _unit;
	_in_house = _unit call KK_fnc_inHouse;
	if (_in_house select 0) then {
		if (_uni in _urban) then {
			_camoIndex = _camoIndex * _uniVal;
		};
	} else {
		switch (true) do {
			case ((_mat in _wood) and (_uni in _wood)): {_camoIndex = _camoIndex * _uniVal;};
			case ((_mat in _wood) and (_uni in _ghillie)): {_camoIndex = _camoIndex * _uniVal * 0.7;};
			case ((_mat in _desert) and (_uni in _desert)): {_camoIndex = _camoIndex * _uniVal;};
			case ((_mat in _snow) and (_uni in _snow)): {_camoIndex = _camoIndex * _uniVal;};
			default {};
		};
	};


	_web = vest _unit;
	if (_in_house select 0) then {
		if ((_web in _urban) || (_web in _trans)) then {
			_camoIndex = _camoIndex * _webVal;
		};
	} else {
		switch (true) do {
			case ((_mat in _wood) and (_web in _wood)): {_camoIndex = _camoIndex * _webVal;};
			case ((_mat in _desert) and (_web in _desert)): {_camoIndex = _camoIndex * _webVal;};
			case ((_mat in _snow) and (_web in _snow)): {_camoIndex = _camoIndex * _webVal;};
			case (_web in _trans): {
				switch (true) do {
					case ((_mat in _wood) and (_uni in _wood)): {_camoIndex = _camoIndex * _webVal;};
					case ((_mat in _desert) and (_uni in _desert)): {_camoIndex = _camoIndex * _webVal;};
					case ((_mat in _snow) and (_uni in _snow)): {_camoIndex = _camoIndex * _webVal;};
				};
				default {};
			};
		};
	};

	_hat = headGear _unit;
	if (_in_house select 0) then {
		if (_hat in _urban) then {
			_camoIndex = _camoIndex * _hatVal;
		};		
	} else {
		switch (true) do {
			case ((_mat in _wood) and (_hat in _wood)): {_camoIndex = _camoIndex * _hatVal;};
			case ((_mat in _desert) and (_hat in _desert)): {_camoIndex = _camoIndex * _hatVal;};
			case ((_mat in _snow) and (_hat in _snow)): {_camoIndex = _camoIndex * _hatVal;};
			default {};
		};
	};


	if (!(_in_house select 0)) then {
		//Handling Tree Proximity

		_nearPlants = count nearestTerrainObjects [_unit, ["TREE","SMALL TREE","BUSH"], 5, false];
		_plantBonus = 1 - ((_nearplants min 5) * 0.03);

		if (_uni in _wood) then {
			_plantBonus = _plantBonus * 0.9;
		};
		if (_uni in _ghillie) then {
			_plantBonus = _plantBonus * 0.7;
		};
		if (_web in _wood) then {
			_plantBonus = _plantBonus * 0.9;
		};
		if (_hat in _wood) then {
			_plantBonus = _plantBonus * 0.9;
		};
		if (_nearPlants > 0) then {
			_camoIndex = _camoIndex * _plantBonus;
		};

		//Handling Building Proximity

		_nearBuilding = (count nearestTerrainObjects [_unit, ["building","house"], 50, false]) min 10;
		_buildingBonus = _nearBuilding / 10;
		_tmpCamoIndex = _camoIndex;

		if (_uni in _urban) then {
			_tmpCamoIndex = _tmpCamoIndex * _uniVal;
		};
		if (_uni in _ghillie) then {
			_tmpCamoIndex = _tmpCamoIndex / _uniVal;
		};
		if (_web in _urban) then {
			_tmpCamoIndex = _tmpCamoIndex * _webVal;
		};
		if (_hat in _urban) then {
			_tmpCamoIndex = _tmpCamoIndex * _hatVal;
		};

		_camoIndex = (_tmpCamoIndex * _buildingBonus) + (_camoIndex * (1 - _buildingBonus));

		// Handle case where the unit is in a bush - regardless of anything give a huge boost to camo
		if (_plantBonus < 1) then {
			_bushes = nearestTerrainObjects [position _unit, ["TREE", "SMALL TREE", "BUSH"], 5];
			if (count _bushes > 0) then {
				_bush = (nearestTerrainObjects [position _unit, ["TREE", "SMALL TREE", "BUSH"], 5]) select 0;
				_radius = ((boundingBoxReal _bush) select 2) / 2;
				_dist = _unit distance _bush;
				if (_dist < _radius) then {
					_camoIndex = _camoIndex * ((_dist / _radius) max 0.4);
				};
			};
		};

	};

	//Lighting Handling

	_light = ((getLightingAt _unit select 1) * 0.8) + ((getLightingAt _unit select 3) * 0.2);

	_camoIndex = _camoIndex + (_light / 2); //modifer simply to make optimum camo selection in peak daylight equal ~.4

	//Speed Handling

	_speed = speed _unit;

	_speedMod = linearConversion [0, 20, _speed, 0.8, 1.2, true];

	_camoIndex = _camoIndex * _speedMod;

	_stanceMod = 1;
	if ( stance _unit == 'CROUCH') then {
		_stanceMod = 0.8;
	};

	if ( stance _unit == 'PRONE') then {
		_stanceMod = 0.6;
	};

	_camoIndex = _camoIndex * _stanceMod;

	_camoIndex = _camoIndex min 2.0;

	_unit setUnitTrait ["camouflageCoef",_camoIndex];

	//Noise system --  default humans are .05, cars are 5, jets are 60

	_audioIndex = ((_speed / 200) min 0.1) max 0.02;

	_unit setUnitTrait ["audibleCoef",_audioIndex];

	if (_debug == 1) then {
		systemChat "audibleCoef =";
		_actualAudio = _unit getUnitTrait "audibleCoef";
		systemChat str _actualAudio;

		systemChat "camouflageCoef =";
		_actualCamo = _unit getUnitTrait "camouflageCoef";
		systemChat str _actualCamo;
		
		if (!(_mat in _wood) and !(_mat in _desert) and !(_mat in _urban) and !(_mat in _snow)) then {hint _mat}; //Debug Function to find unlogged terrain
	};
};

while {alive _this} do {
	[_this] call _camoFnc;
	sleep 1;
};